Feat/topic classifier
deeppavlov/DeepPavlov pull request #1584
Opened 2022-07-26 14:55 UTC by dilyararimovna

2022-10-25 13:07 UTC, vaskonov requested changes

2022-10-25 13:33 UTC, dilyararimovna commented on deeppavlov/configs/classifiers/topics_bert_base_multilingual_uncased.json
> +{
![tvoe-vyrazhenie-lica_65914110_orig_](https://user-images.githubusercontent.com/14152126/197787271-2a239298-2325-48eb-9b96-8117440ab014.jpeg)

2022-10-26 12:16 UTC, dilyararimovna commented
тесты не проходят. но не из-за моего нового конфига
![nelzya-prosto-tak-vzyat-i-boromir-mem_193835087_orig_](https://user-images.githubusercontent.com/14152126/198023698-5eb9e0ac-2906-45ff-a7a5-67aa20ec86c5.jpg)

2022-10-31 06:05 UTC, IgnatovFedor approved these changes

2022-10-31 09:05 UTC, merged