Feat/odqa improve
deeppavlov/DeepPavlov pull request #1635
Opened 2023-04-02 15:50 UTC by dmitrijeuseew

ODQA, improve quality and reduce RAM consumption by adding Binary Passage Retrieval and optimizing tfidf index.

2023-04-28 06:56 UTC, IgnatovFedor requested changes

2023-04-28 06:56 UTC, IgnatovFedor commented on deeppavlov/models/torch_bert/torch_transformers_squad.py
> +                 psg_cls: bool = False,
docstring

2023-04-28 06:56 UTC, IgnatovFedor commented on deeppavlov/models/doc_retrieval/bpr.py
> +    return list_u
move to separated module. If you keep it here, you will need to add concat_lists to requirements registry

2023-04-28 06:56 UTC, IgnatovFedor commented on deeppavlov/configs/squad/qa_nq_psgcls_bert.json
> +        "url": "http://files.deeppavlov.ai/tmp/nq_psgcls_bert.tar.gz",
tmp

2023-04-29 20:37 UTC, dmitrijeuseew commented on deeppavlov/configs/doc_retrieval/ru_ranker_tfidf_wiki.json
> +        "top_n": 100,
Yes, more extracted paragraphs increase the probability to contain the correct answer.

2023-05-11 14:11 UTC, IgnatovFedor requested changes

2023-05-11 14:11 UTC, IgnatovFedor commented on deeppavlov/configs/doc_retrieval/en_ranker_pop_wiki.json
> -        "pop_dict_path": "{DOWNLOADS_PATH}/odqa/enwiki20180211_popularities.json",
still used in tests/test_configs/doc_retrieval/en_ranker_pop_wiki_test.json
Update test config

2023-05-11 14:11 UTC, IgnatovFedor commented on deeppavlov/configs/doc_retrieval/en_ranker_pop_wiki.json
> +        "url": "http://files.deeppavlov.ai/deeppavlov_data/odqa/enwiki_popularities.tar.gz",
shouldn't file be in datasets section like enwiki20180211_popularities was?

2023-05-11 14:11 UTC, IgnatovFedor commented on deeppavlov/configs/doc_retrieval/en_ranker_pop_wiki.json
> +        "url": "http://files.deeppavlov.ai/deeppavlov_data/odqa/enwiki_l100.tar.gz",
shouldn't be in datasets directory like enwiki.tar.gz was?

2023-05-11 14:11 UTC, IgnatovFedor commented on deeppavlov/configs/doc_retrieval/en_ranker_tfidf_wiki.json
> +        "url": "http://files.deeppavlov.ai/deeppavlov_data/odqa/enwiki_l100.tar.gz",
shouldn't be in datasets section?

2023-05-11 14:11 UTC, IgnatovFedor commented on deeppavlov/configs/doc_retrieval/ru_ranker_tfidf_wiki.json
> +        "url": "http://files.deeppavlov.ai/deeppavlov_data/odqa/ruwiki_par_page_compr.tar.gz",
shouldn't be in datasets directory?

2023-05-11 14:11 UTC, IgnatovFedor commented on deeppavlov/configs/odqa/en_odqa_pop_infer_wiki.json
> +    ]
empty

2023-05-11 14:11 UTC, IgnatovFedor commented on deeppavlov/configs/odqa/en_odqa_pop_infer_wiki.json
> +{
Shouldn't this config replace en_odqa_infer_wiki? What benefits do we have from keeping two English odqa models?

2023-05-25 10:56 UTC, IgnatovFedor commented on deeppavlov/configs/doc_retrieval/en_ranker_pop_wiki.json
> +        "url": "http://files.deeppavlov.ai/deeppavlov_data/odqa/enwiki_l100.tar.gz",
is database

2023-05-25 10:57 UTC, IgnatovFedor commented on deeppavlov/configs/doc_retrieval/en_ranker_tfidf_wiki.json
> +        "url": "http://files.deeppavlov.ai/deeppavlov_data/odqa/enwiki_l100.tar.gz",
is database

2023-05-25 11:09 UTC, IgnatovFedor requested changes

2023-05-25 11:09 UTC, IgnatovFedor commented on deeppavlov/configs/doc_retrieval/en_ranker_tfidf_wiki.json
> +      "ROOT_PATH": "/archive/evseev/.deeppavlov",
wrong path

2023-06-16 05:36 UTC, IgnatovFedor approved these changes

2023-06-16 05:46 UTC, merged